// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poudlard.Infrastructure.Database.Context;

#nullable disable

namespace Poudlard.Infrastructure.Migrations
{
    [DbContext(typeof(PoudlardContext))]
    [Migration("20260128220555_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Poudlard.Domain.Entities.Personne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type_personne")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Personne");

                    b.HasDiscriminator<string>("Type_personne").HasValue("Personne");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Poudlard.Domain.Entities.Moldu", b =>
                {
                    b.HasBaseType("Poudlard.Domain.Entities.Personne");

                    b.HasDiscriminator().HasValue("Moldu");
                });

            modelBuilder.Entity("Poudlard.Domain.Entities.Sorcier", b =>
                {
                    b.HasBaseType("Poudlard.Domain.Entities.Personne");

                    b.Property<string>("Baguette")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("NON_RENSEIGNEE");

                    b.Property<bool>("FideleVoldemort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PeutEntrerPoudlard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasDiscriminator().HasValue("Sorcier");
                });

            modelBuilder.Entity("Poudlard.Domain.Entities.Eleve", b =>
                {
                    b.HasBaseType("Poudlard.Domain.Entities.Sorcier");

                    b.Property<int>("Annee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Maison")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("None");

                    b.Property<int?>("PointGagne")
                        .HasColumnType("int");

                    b.Property<int?>("PointPerdu")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Eleve");
                });

            modelBuilder.Entity("Poudlard.Domain.Entities.Professeur", b =>
                {
                    b.HasBaseType("Poudlard.Domain.Entities.Sorcier");

                    b.Property<bool>("ChefMaison")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("CourAttribue")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Maison")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("None");

                    b.ToTable("Personne", t =>
                        {
                            t.Property("Maison")
                                .HasColumnName("Professeur_Maison");
                        });

                    b.HasDiscriminator().HasValue("Prof");
                });
#pragma warning restore 612, 618
        }
    }
}
